#!/usr/bin/env ruby


require 'lib/sandbox/sandbox'
require 'net/http'


def run_url(url)
  result = Net::HTTP.get(URI.parse(url))

  Thread.start do
    sandbox = Sandbox.new
    sandbox.taint

    $SAFE = 4
    begin
      sandbox.instance_eval(result, url)
    rescue
      sandbox.say($!.to_s)
    ensure
      if $!
        sandbox.say $!.message + "\n"
      end
    end
  end
end

# create a window

require 'gtk2'

window = Gtk::Window.new
window.title = "GG_Browser"
window.default_width = 800
window.default_height = 600

window.signal_connect('destroy') do
  Gtk.main_quit
end

entry = Gtk::Entry.new
entry.set_size_request 700, 25 # width, height
entry.text = "http://ggtest.bashquest.com/index.rb"
entry.signal_connect('activate') do |obj|
  run_url(obj.text)
end

layout = Gtk::Layout.new
layout.put entry, 10, 10 # child_widget, x, y

window.add layout
window.show_all

Gtk.main
