#!/usr/bin/env ruby


require 'lib/sandbox/sandbox'
require 'net/http'


result = Net::HTTP.get(URI.parse("http://ggtest.bashquest.com/index.rb"))

Thread.start do
  sandbox = Sandbox.new
  sandbox.taint

  $SAFE = 4
  begin
    sandbox.instance_eval(result)
  rescue
    sandbox.say($!.to_s)
  end
end

# create a window

require 'gtk2'

window = Gtk::Window.new
window.title = "GG_Browser"

window.signal_connect('destroy') do
  Gtk.main_quit
end

entry = Gtk::Entry.new
entry.set_size_request 130, 25 # width, height
entry.text = "http://ggtest.bashquest.com/index.rb"

layout = Gtk::Layout.new
layout.put entry, 10, 10 # child_widget, x, y

window.add layout
window.show_all

Gtk.main
